/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import java.lang.String;

/**
 *
 * @author Pedro
 */
public class interfaz extends javax.swing.JFrame {

    controlador controlador;
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        controlador = new controlador (this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pestañaproyectos = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        TextoNombreEmpleado = new javax.swing.JLabel();
        CampoNombreEmpleados = new javax.swing.JTextField();
        TextoApellidosEmpleados = new javax.swing.JLabel();
        CampoApellidosEmpleados = new javax.swing.JTextField();
        TextoAñonacimientoEmpleados = new javax.swing.JLabel();
        CampoAñonacimientoEmpleados = new javax.swing.JTextField();
        TextoNIFEmpleados = new javax.swing.JLabel();
        CampoNIFEmpleados = new javax.swing.JTextField();
        BotonEliminarEmpleados = new javax.swing.JButton();
        BotonIntroducirEmpleados = new javax.swing.JButton();
        BotonModificarEmpleados = new javax.swing.JButton();
        ComboboxAsociar = new javax.swing.JComboBox<>();
        TextoProyectoAsociar = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        BotonAsociarEmpleados = new javax.swing.JButton();
        ComboboxListarProyectos = new javax.swing.JComboBox<>();
        BotonVerAsociaciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAsociaciones = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        TextoTituloProyecto = new javax.swing.JLabel();
        CampoTituloProyectos = new javax.swing.JTextField();
        TextoFechainicioProyectos = new javax.swing.JLabel();
        TextoFechafinProyectos = new javax.swing.JLabel();
        CampoFechainicioProyectos = new javax.swing.JTextField();
        CampoFechafinProyectos = new javax.swing.JTextField();
        CampoDescripcionProyectos = new javax.swing.JTextField();
        TextoDescripcionProyectos = new javax.swing.JLabel();
        BotonIntroducirProyectos = new javax.swing.JButton();
        BotonModificarProyectos = new javax.swing.JButton();
        BotonEliminarProyectos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProyectos = new javax.swing.JTable();
        ComboboxListarEmpleados = new javax.swing.JComboBox<>();
        BotonListarEmpleados = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaEmpleados1 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        TextoNombreEmpleado.setText("Nombre:");

        CampoNombreEmpleados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CampoNombreEmpleadosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        TextoApellidosEmpleados.setText("Apellidos:");

        CampoApellidosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApellidosEmpleadosActionPerformed(evt);
            }
        });

        TextoAñonacimientoEmpleados.setText("Año de Nacimiento:");

        CampoAñonacimientoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAñonacimientoEmpleadosActionPerformed(evt);
            }
        });

        TextoNIFEmpleados.setText("NIF:");

        CampoNIFEmpleados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CampoNombreEmpleadosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CampoNIFEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNIFEmpleadosActionPerformed(evt);
            }
        });

        BotonEliminarEmpleados.setText("Eliminar");
        BotonEliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarEmpleadosActionPerformed(evt);
            }
        });

        BotonIntroducirEmpleados.setText("Introducir");

        BotonModificarEmpleados.setText("Modificar");

        ComboboxAsociar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TextoProyectoAsociar.setText("Asociar a proyecto:");

        TablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaEmpleados);

        BotonAsociarEmpleados.setText("Asociar");

        ComboboxListarProyectos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonVerAsociaciones.setText("Ver asociación");
        BotonVerAsociaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerAsociacionesActionPerformed(evt);
            }
        });

        TablaAsociaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaAsociaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsociacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaAsociaciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(81, 596, Short.MAX_VALUE)
                .addComponent(BotonAsociarEmpleados)
                .addGap(84, 84, 84))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TextoAñonacimientoEmpleados)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoAñonacimientoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ComboboxListarProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonVerAsociaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(BotonIntroducirEmpleados)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonModificarEmpleados)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonEliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(TextoProyectoAsociar)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboboxAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TextoNombreEmpleado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CampoNombreEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)
                                        .addComponent(TextoApellidosEmpleados)
                                        .addGap(18, 18, 18)
                                        .addComponent(CampoApellidosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TextoNIFEmpleados)
                                        .addGap(18, 18, 18)
                                        .addComponent(CampoNIFEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNombreEmpleado)
                    .addComponent(CampoNombreEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoApellidosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoApellidosEmpleados))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoNIFEmpleados)
                            .addComponent(CampoNIFEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboboxListarProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonVerAsociaciones))
                            .addComponent(BotonAsociarEmpleados)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoAñonacimientoEmpleados)
                            .addComponent(CampoAñonacimientoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonIntroducirEmpleados)
                            .addComponent(BotonEliminarEmpleados)
                            .addComponent(BotonModificarEmpleados)
                            .addComponent(TextoProyectoAsociar)
                            .addComponent(ComboboxAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pestañaproyectos.addTab("Empleados", jPanel2);

        TextoTituloProyecto.setText("Título:");

        CampoTituloProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTituloProyectosActionPerformed(evt);
            }
        });

        TextoFechainicioProyectos.setText("Fecha Inicio:");

        TextoFechafinProyectos.setText("Fecha Fin:");

        CampoFechainicioProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechainicioProyectosActionPerformed(evt);
            }
        });

        CampoFechafinProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechafinProyectosActionPerformed(evt);
            }
        });

        CampoDescripcionProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDescripcionProyectosActionPerformed(evt);
            }
        });

        TextoDescripcionProyectos.setText("Descripción:");

        BotonIntroducirProyectos.setText("Introducir");

        BotonModificarProyectos.setText("Modificar");

        BotonEliminarProyectos.setText("Eliminar");

        TablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProyectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProyectos);

        ComboboxListarEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonListarEmpleados.setText("Listar empleado");
        BotonListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarEmpleadosActionPerformed(evt);
            }
        });

        TablaEmpleados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleados1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TablaEmpleados1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(TextoTituloProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoTituloProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoDescripcionProyectos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoDescripcionProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoFechainicioProyectos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoFechafinProyectos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoFechafinProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoFechainicioProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(BotonIntroducirProyectos)
                                .addGap(72, 72, 72)
                                .addComponent(BotonModificarProyectos)
                                .addGap(86, 86, 86)
                                .addComponent(BotonEliminarProyectos))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(ComboboxListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(BotonListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoTituloProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoTituloProyecto))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CampoFechainicioProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoFechainicioProyectos)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TextoDescripcionProyectos)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoFechafinProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFechafinProyectos)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CampoDescripcionProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonIntroducirProyectos)
                    .addComponent(BotonModificarProyectos)
                    .addComponent(BotonEliminarProyectos))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboboxListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonListarEmpleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pestañaproyectos.addTab("Proyectos", jPanel3);

        getContentPane().add(pestañaproyectos, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoApellidosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidosEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidosEmpleadosActionPerformed

    private void BotonEliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarEmpleadosActionPerformed

    private void CampoNIFEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNIFEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNIFEmpleadosActionPerformed

    private void CampoAñonacimientoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAñonacimientoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAñonacimientoEmpleadosActionPerformed

    private void CampoNombreEmpleadosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CampoNombreEmpleadosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreEmpleadosAncestorAdded

    private void TablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaEmpleadosMouseClicked

    private void CampoFechainicioProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechainicioProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechainicioProyectosActionPerformed

    private void CampoTituloProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTituloProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTituloProyectosActionPerformed

    private void CampoFechafinProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechafinProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechafinProyectosActionPerformed

    private void CampoDescripcionProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDescripcionProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDescripcionProyectosActionPerformed

    private void TablaProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProyectosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaProyectosMouseClicked

    private void BotonVerAsociacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerAsociacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVerAsociacionesActionPerformed

    private void BotonListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListarEmpleadosActionPerformed

    private void TablaAsociacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsociacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaAsociacionesMouseClicked

    private void TablaEmpleados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleados1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaEmpleados1MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAsociarEmpleados;
    public javax.swing.JButton BotonEliminarEmpleados;
    public javax.swing.JButton BotonEliminarProyectos;
    public javax.swing.JButton BotonIntroducirEmpleados;
    public javax.swing.JButton BotonIntroducirProyectos;
    public javax.swing.JButton BotonListarEmpleados;
    public javax.swing.JButton BotonModificarEmpleados;
    public javax.swing.JButton BotonModificarProyectos;
    public javax.swing.JButton BotonVerAsociaciones;
    public javax.swing.JTextField CampoApellidosEmpleados;
    public javax.swing.JTextField CampoAñonacimientoEmpleados;
    public javax.swing.JTextField CampoDescripcionProyectos;
    public javax.swing.JTextField CampoFechafinProyectos;
    public javax.swing.JTextField CampoFechainicioProyectos;
    public javax.swing.JTextField CampoNIFEmpleados;
    public javax.swing.JTextField CampoNombreEmpleados;
    public javax.swing.JTextField CampoTituloProyectos;
    public javax.swing.JComboBox<String> ComboboxAsociar;
    public javax.swing.JComboBox<String> ComboboxListarEmpleados;
    public javax.swing.JComboBox<String> ComboboxListarProyectos;
    public javax.swing.JTable TablaAsociaciones;
    public javax.swing.JTable TablaEmpleados;
    public javax.swing.JTable TablaEmpleados1;
    public javax.swing.JTable TablaProyectos;
    private javax.swing.JLabel TextoApellidosEmpleados;
    private javax.swing.JLabel TextoAñonacimientoEmpleados;
    private javax.swing.JLabel TextoDescripcionProyectos;
    private javax.swing.JLabel TextoFechafinProyectos;
    private javax.swing.JLabel TextoFechainicioProyectos;
    private javax.swing.JLabel TextoNIFEmpleados;
    private javax.swing.JLabel TextoNombreEmpleado;
    private javax.swing.JLabel TextoProyectoAsociar;
    private javax.swing.JLabel TextoTituloProyecto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane pestañaproyectos;
    // End of variables declaration//GEN-END:variables
}
